# Generated by Django 5.1.5 on 2025-02-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Alumno',
        ),
    ]
